# Generated by Django 3.2.8 on 2021-10-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211031_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectversion'),
        ),
    ]
