# Generated by Django 3.1.7 on 2021-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='email',
            field=models.EmailField(default='adminp@pattren.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
