# Generated by Django 3.1.7 on 2021-02-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_auto_20210225_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='platform',
            field=models.CharField(default='android', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
