# Generated by Django 3.1.5 on 2021-01-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_apps', '0002_auto_20210106_1450'),
        ('myboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myboard',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui_apps.uiimages'),
        ),
    ]
