# Generated by Django 3.1.7 on 2021-04-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_apps', '0006_auto_20210429_2228'),
        ('myboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myboard',
            name='images',
        ),
        migrations.CreateModel(
            name='MyBoardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui_apps.uiimages')),
            ],
        ),
    ]
