# Generated by Django 3.1.7 on 2021-05-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myboards', '0002_auto_20210429_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='myboarditem',
            name='myboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myboards.myboard'),
            preserve_default=False,
        ),
    ]
