# Generated by Django 3.2.8 on 2021-10-28 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myboards', '0004_auto_20210625_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myboard',
            old_name='name',
            new_name='board_name',
        ),
        migrations.AddField(
            model_name='myboard',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='myboard',
            unique_together={('user', 'board_name')},
        ),
    ]
