# Generated by Django 3.2.8 on 2021-10-29 12:36

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myboards', '0005_auto_20211028_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboard',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['board_name']),
        ),
    ]
