# Generated by Django 3.2.8 on 2021-10-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboards', '0006_alter_myboard_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myboard',
            unique_together=set(),
        ),
    ]
