# Generated by Django 3.2.8 on 2021-10-30 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myboards', '0007_alter_myboard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboard',
            name='board_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='myboard',
            unique_together={('user', 'board_name')},
        ),
    ]
