# Generated by Django 3.2.8 on 2021-10-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboards', '0008_auto_20211030_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboard',
            name='board_name',
            field=models.CharField(max_length=50),
        ),
    ]
