# Generated by Django 3.2.8 on 2021-10-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboards', '0009_alter_myboard_board_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myboard',
            unique_together=set(),
        ),
    ]
