# Generated by Django 3.1.6 on 2021-02-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UiApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='apps/')),
            ],
            options={
                'verbose_name': 'User Interface Apps',
                'verbose_name_plural': 'User Interface Apps',
            },
        ),
        migrations.CreateModel(
            name='UiImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apps/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ui_apps.category')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ui_apps.platform')),
                ('uiapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_apps.uiapps')),
            ],
        ),
    ]
