# Generated by Django 3.1.7 on 2021-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_apps', '0002_auto_20210225_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiapps',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
