# Generated by Django 3.1.5 on 2021-01-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_apps', '0002_auto_20210106_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiimages',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ui_apps.platform'),
            preserve_default=False,
        ),
    ]
