# Generated by Django 3.1.7 on 2021-06-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_apps', '0006_auto_20210429_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uiimages',
            name='category',
        ),
    ]
